# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.27)
{
  # A helpful description of your flake
  description = "Flake para desarrollar y empacar antispam";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };

  # Flake outputs that other flakes can use
  outputs =
    {
      self,
      flake-schemas,
      nixpkgs,
    }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [
        "x86_64-linux"
        "aarch64-darwin"
        "x86_64-darwin"
        "aarch64-linux"
      ];
      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            pkgs = import nixpkgs { inherit system; };
          }
        );
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      packages = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.buildGoModule {
            pname = "antispam";
            version = "0.1.0"; # cámbialo cuando hagas release

            src = ./.;

            vendorHash = "sha256-tz0zFPR5cm1eNZcXyxM2LZJcD4E1KzNkMt2TnQCtr8c=";

            # Dependencias nativas
            nativeBuildInputs = [
              pkgs.makeWrapper
              pkgs.emacs
            ];

            # Instalamos también los archivos Elisp
            postInstall = ''
              mkdir -p $out/share/emacs-antispam
              cp -r ./lisp $out/share/emacs-antispam/

              # Envolvemos el binario para que sepa dónde está emacs-quiz.el
              wrapProgram $out/bin/antispam \
                --set EMACS_QUIZ_EL "$out/share/emacs-antispam/lisp/emacs-quiz.el" \
                --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.emacs ]}
            '';

            meta = with pkgs.lib; {
              description = "Bot anti-spam para canal de GNU Emacs";
              homepage = "https://github.com/shackra/antispam";
              license = licenses.gpl3Plus;
              maintainers = [ lib.maintainers.shackra ];
              platforms = supportedSystems;
            };
          };
        }
      );

      # Development environments
      devShells = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.mkShell {
            # Pinned packages available in the environment
            packages = with pkgs; [
              go
              nil
              emacs
              self.packages.${stdenv.hostPlatform.system}.default
            ];
          };
        }
      );

      nixosModules.default =
        {
          config,
          lib,
          pkgs,
          ...
        }:
        let
          cfg = config.services.emacs-antispam-bot;
          pkg = self.packages.${pkgs.stdenv.hostPlatform.system}.default;
        in
        {
          options.services.emacs-antispam-bot = {
            enable = lib.mkEnableOption "Bot anti-spam para canal de GNU Emacs en Español";

            tokenFile = lib.mkOption {
              type = lib.types.path;
              description = "Ruta al archivo que contiene TELEGRAM_BOT_TOKEN (recomendado con agenix/sops)";
              example = "/run/agenix/telegram-bot-token";
            };

            dataDir = lib.mkOption {
              type = lib.types.str;
              default = "/var/lib/emacs-antispam";
              description = "Directorio de datos (BadgerDB)";
            };
          };

          config = lib.mkIf cfg.enable {
            users.users.emacsbot = {
              isSystemUser = true;
              group = "emacsbot";
              home = cfg.dataDir;
              createHome = true;
            };
            users.groups.emacsbot = { };

            systemd.services.emacs-antispam-bot = {
              description = "Bot anti-spam para el canal de GNU Emacs en Español";
              after = [ "network.target" ];
              wantedBy = [ "multi-user.target" ];

              serviceConfig = {
                Type = "simple";
                User = "emacsbot";
                Group = "emacsbot";
                WorkingDirectory = cfg.dataDir;
                ExecStart = "${pkg}/bin/antispam";
                Restart = "always";
                RestartSec = "5s";

                NoNewPrivileges = true;
                PrivateTmp = true;
                ProtectSystem = "strict";
                ReadWritePaths = [ cfg.dataDir ];
                EnvironmentFile = [ cfg.tokenFile ];
              };
            };

            systemd.tmpfiles.rules = [
              "d ${cfg.dataDir} 0750 emacsbot emacsbot -"
            ];
          };
        };
    };
}
